language: go

go:
- 1.12.x

env:
- GO111MODULE=on
  matrix:
    - TARGET="build"
    - TARGET="buildarm7"
    - TARGET="test"
script: make $TARGET

after_success:
  - bash <(curl -s https://codecov.io/bash)
